/**
 * Mock / Demo AI Review Artifacts
 * 
 * NOTE: These are static simulation artifacts for testing the canonical model.
 * They are NOT generated by an external live AI model provider.
 */

import type { AIReviewArtifact } from '../types/aiReview';
import { 
  AIReviewTargetType, 
  AIReviewCategory, 
  AIReviewSeverity, 
  AIFactualFlag, 
  AIReviewExecutionState 
} from '../types/aiReview';

export const MOCK_AI_REVIEWS: AIReviewArtifact[] = [
  // 1. News Domain Review: news-sudan-101 (Blue Nile Flood Alert)
  {
    id: 'ai-rev-news-101',
    target: {
      targetType: AIReviewTargetType.News,
      targetId: 'news-sudan-101',
      sourceUpdatedAt: '2026-09-14T11:20:00Z',
    },
    generatedAt: '2026-09-14T11:25:00Z',
    executionState: AIReviewExecutionState.Completed,
    providerId: 'mock-audit-engine',
    isAdvisoryOnly: true,
    findings: [
      {
        id: 'find-news-01',
        category: AIReviewCategory.SourceReferenceQuality,
        severity: AIReviewSeverity.ReviewRecommended,
        flag: AIFactualFlag.SourceCheckSuggested,
        message: 'يُنصح بمطابقة أرقام مناسيب النيل مع التقرير اليومي الصادر عن محطة الدمازين.',
        sourceLanguage: 'ar',
        affectedField: 'sources',
        suggestion: 'إضافة رابط أو مرجع رسمي لبيان وزارة الري والموارد المائية الصادر صباح اليوم.',
      },
      {
        id: 'find-news-02',
        category: AIReviewCategory.Completeness,
        severity: AIReviewSeverity.Info,
        message: 'المقال يستوفي عناصر الإحاطة الإخبارية الأساسية وتحديد النطاق الجغرافي (سنار والدمازين).',
        sourceLanguage: 'ar',
        affectedField: 'summaryAr',
      },
    ],
  },

  // 2. Library Domain Review: doc-201 (Waste Management Law)
  {
    id: 'ai-rev-lib-201',
    target: {
      targetType: AIReviewTargetType.LibraryDocument,
      targetId: 'doc-201',
      sourceUpdatedAt: '2020-10-13',
    },
    generatedAt: '2026-09-15T09:00:00Z',
    executionState: AIReviewExecutionState.Completed,
    providerId: 'mock-audit-engine',
    isAdvisoryOnly: true,
    findings: [
      {
        id: 'find-lib-01',
        category: AIReviewCategory.RightsConcern,
        severity: AIReviewSeverity.ReviewRecommended,
        flag: AIFactualFlag.NeedsReview,
        message: 'الوثيقة منسوبة لجريدة رسمية حكومية؛ يُرجى التحقق من حالة حقوق النشر وإعادة التوزيع قبل النشر المفتوح.',
        sourceLanguage: 'ar',
        affectedField: 'rightsStatus',
        suggestion: 'تأكيد حالة الحقوق كـ "OpenPubliclyAvailable" أو إرفاق إشعار ترخيص النشر الحكومي.',
      },
      {
        id: 'find-lib-02',
        category: AIReviewCategory.MetadataCompleteness,
        severity: AIReviewSeverity.Info,
        message: 'تم توثيق بيانات الجهة المصدرة والتصنيف البيئي بشكل سليم.',
        sourceLanguage: 'ar',
        affectedField: 'organizationId',
      },
    ],
  },

  // 3. Training Domain Review: course-01 (Environmental Journalism Course)
  {
    id: 'ai-rev-tr-01',
    target: {
      targetType: AIReviewTargetType.TrainingCourse,
      targetId: 'course-01',
      sourceUpdatedAt: '2026-02-10T10:00:00Z',
    },
    generatedAt: '2026-02-10T10:05:00Z',
    executionState: AIReviewExecutionState.Completed,
    providerId: 'mock-audit-engine',
    isAdvisoryOnly: true,
    findings: [
      {
        id: 'find-tr-01',
        category: AIReviewCategory.Clarity,
        severity: AIReviewSeverity.Info,
        message: 'وصف الفئة المستهدفة وساعات التدريب محدد بوضوح للمستوى المبتدئ.',
        sourceLanguage: 'ar',
        affectedField: 'targetAudienceAr',
        suggestion: 'يمكن إضافة قائمة مراجع تمهيدية مقترحة للمتدربين في تحديث لاحق.',
      },
    ],
  },

  // 4. Community / Citizen Submission Review: sub-001 (White Nile water level drop)
  {
    id: 'ai-rev-comm-001',
    target: {
      targetType: AIReviewTargetType.CitizenSubmission,
      targetId: 'sub-001',
      sourceUpdatedAt: '2026-09-16T10:00:00Z',
    },
    generatedAt: '2026-09-16T10:05:00Z',
    executionState: AIReviewExecutionState.Completed,
    providerId: 'mock-audit-engine',
    isAdvisoryOnly: true,
    findings: [
      {
        id: 'find-comm-01',
        category: AIReviewCategory.PossibleInconsistency,
        severity: AIReviewSeverity.Warning,
        flag: AIFactualFlag.NeedsReview,
        message: 'البلاغ الميداني يشير إلى انحسار مياه النيل الأبيض في جبل أولياء؛ يلزم التحقق الصحفي من بيانات السد والتحكم.',
        sourceLanguage: 'ar',
        affectedField: 'body',
        suggestion: 'توجيه البلاغ لفريق التغطية الإخبارية للتحقق الميداني دون تغيير حالة البلاغ تلقائياً.',
      },
    ],
  },

  // 5. Archived / Removed Target Example (Demonstrates graceful missing target handling)
  {
    id: 'ai-rev-archived-05',
    target: {
      targetType: AIReviewTargetType.News,
      targetId: 'news-archived-999',
      sourceUpdatedAt: '2024-01-01T00:00:00Z',
    },
    generatedAt: '2024-01-01T01:00:00Z',
    executionState: AIReviewExecutionState.Completed,
    providerId: 'mock-audit-engine',
    isAdvisoryOnly: true,
    findings: [
      {
        id: 'find-arch-01',
        category: AIReviewCategory.Completeness,
        severity: AIReviewSeverity.Info,
        message: 'تقرير تدقيق أرشيفي لمحتوى لم يعد متوفراً في قاعدة البيانات الحالية.',
        sourceLanguage: 'ar',
      },
    ],
  },
];
